[theme]
primaryColor = "#FF441F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#222222"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
